name: crawl

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  crawl:
    name: Crawl Algolia search index

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: "RYAT0G9BU3"
          algolia_api_key: ${{secrets.ALGOLIA_API_KEY}}
          file: ".algolia/config.json"
